name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Material for MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material==5.1.0
          pip install mkdocs-macros-plugin

      - name: Deploy
        env:
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
        run: |
          git pull
          mkdocs gh-deploy --clean
